### Register
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "email": "newuser1@gmail.com",
  "password": "123456",
  "fullName": "Nguyen Van A"
}

### Login
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "newuser1@gmail.com",
  "password": "123456"
}

### Register Debug
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "email": "debug2@gmail.com",
  "password": "123456",
  "fullName": "Debug Two"
}
