spring.application.name=main

spring.datasource.url=jdbc:mysql://localhost:3306/cloudcvhub?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1746
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT Configuration
# Key secret bắt buộc phải đủ dài (tối thiểu 256 bits/32 ký tự)
jwt.secret=se_co_nhung_con_cho_phai_tra_gia
# Thời gian sống Access Token: 15 min
jwt.access-token-expiration=900000
# Thời gian sống Refresh Token: 7 ngày
jwt.refresh-token-expiration=604800000
